name: PR
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Clone Repo
         uses: actions/checkout@v2

       - name: Unit tests
         run: ./gradlew test